### ISSUE TITLE
시간표 alias 설정

### ISSUE THREAD

**Issue by nutyworks** [dimigoin/dimigoin-back-v3#132]
3-2
"* 3D 배경ㆍ소품 제작", "* 3D 캐릭터 제작", "* 색채 디자인" -> "애니"

3-3, 3-4
"* 프로그래밍 언어 활용" -> "응개"

3-5, 3-6
"* 네트워크보안관리", "* 네트워크유지보수", "* 인터넷 설비 설계" -> "구축"
"* 네트워크 프로토콜 분석" -> "네프"

2-2
"* 광고 전략 수립", "* 음악콘텐츠제작기획", "* 그래픽 제작" -> "광콘", "음콘", "그래픽"

2-3~6
"자료구조" -> "자료"

1-1, 1-2
"컴퓨터 그래픽" -> "컴그"

**Comment by Gijuno** [comment]
3-2는 "애니" 라고 한다고 합니다.
참고 부탁드려요
