### ISSUE TITLE
인강실 신청 모듈에서 오류 발생 

### ISSUE THREAD

**Issue by cokia** [dimigoin/dimigoin-back-v3#15]
/ingang-application/time/NSS1
해당라우터를 사용해 인강실 신청을 하던 중 오류를 발견했습니다. (with @rycont)

총 두가지 오류가 중첩된것으로 파악되는데, 
첫번째는
https://github.com/dimigoin/dimigoin-back-v3/blob/19fe5a621444b91921520d66937c5f0fe0b75dc1/src/models/ingang-application.ts#L20
에서 this 를 불러오지 못하는 상황입니다. 그래서 임시로 this 대신 'IngangApplicationModel' 로 변경하여 해당 문제는 해결이 가능한것으로 파악이 됩니다.

두번째는 
https://github.com/dimigoin/dimigoin-back-v3/blob/19fe5a621444b91921520d66937c5f0fe0b75dc1/src/models/ingang-application.ts#L22
위에 findOne 구문에서 time 인자를 받아오지 못합니다 (정확하게는 몽고디비 벨리데이션 오류가 **time 파라미터에 대해서만** 
발생합니다). 바로 위에서 time을 디버깅 해보면 정상적인 값이 넘어옴에도 불구하고 받아오지 못하는데 정확히 어떤 이슈인지 파악이 불가능합니다 (위에 스키마에서 time에 대해 required를 빼면 잘 작동하는것으로 보아 벨리데이션 문제가 맞는 것 같습니다)

**Comment by uhmseohun** [comment]
음 리팩터링 하면서 문제 생긴 것 같은데 확인해 보겠습니당
