### ISSUE TITLE
/dalgeurak/waitingLine API 급식 종류 파라미터 미존재

### ISSUE THREAD

**Issue by doch2** [dimigoin/dimigoin-back-v3#151]
급식 대기줄 변경 API에 급식 종류(점심, 저녁)을 지정할 수 있는 파라미터가 있어야 하는데 현재 존재하지 않습니다.

**Comment by omh02033** [comment]
점심,저녁을 선택하면서 안으로 줄서야할지 밖에서 줄서야할지를 정해야할까요?

**Comment by doch2** [comment]
네네 맞습니다 급식 줄 순서 정하는 API 처럼 만들어주시면 될 것 같아요

**Comment by omh02033** [comment]
나눌 필요가 없다고 생각하는게 줄 서야하는거는 상황을 보고 실시간으로 바꿔야해서
그냥 지금처럼 점심 저녁을 합치고 점심 저녁 지나면 자동으로 `corridor` 로 바뀌도록 하는게 차라리 나을거같아요
