### ISSUE TITLE
timetable response형식

### ISSUE THREAD

**Issue by Changemin** [dimigoin/dimigoin-back-v3#17]
`{
    "timetable": [
        {
            "_id": "60152f1afc4f570024b4d15d",
            "date": "2020-06-28T00:00:00.000Z",
            "grade": 2,
            "class": 4,
            "period": 1,
            "subject": "영어",
            "createdAt": "2021-01-30T10:04:10.805Z",
            "updatedAt": "2021-01-30T10:04:10.805Z"
        }
}`

이차원 배열로 부탁드려연 ~~ 유노 왓암세잉

**Comment by uhmseohun** [comment]
<img width="1537" alt="Screen Shot 2021-01-30 at 11 23 24 PM" src="https://user-images.githubusercontent.com/16954420/106358866-27bb8180-6352-11eb-8020-1d0859de8742.png">
별 보러 가실까요 🤗
